### ISSUE TITLE
[Application] for some reason IdleMaster stoped working and the window looks like this

### ISSUE THREAD

**Issue by BatyGamer** [JonasNilson/idle_master_extended#168]
![idle](https://user-images.githubusercontent.com/78668528/107133075-72de1300-68c3-11eb-9288-77700447eb93.PNG)

**Comment by JonasNilson** [comment]
@BatyGamer what version of Idle Master are you running? It looks like the application is in some weird state. Do you have any errors in your `error.log`?

**Comment by PatrickWehri** [comment]
I had the same error yesterday, caused by my own stupidity:
I was running the .exe from within the unextracted .zip file. The client looked the same for me, was able to log into steam, but it would never been detected as running.
Today, after a reboot and actually extracting the .zip, it works fine.

**Comment by soukass** [comment]
@JonasNilson a mi me pasa lo mismo la ventana de idle master tiene se problema , como soluciono el problema? PD: la version que tengo es la v.1.7

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
