### ISSUE TITLE
[Application] Not Farming via link/shortcut

### ISSUE THREAD

**Issue by Der-Floh** [JonasNilson/idle_master_extended#271]
Idle Master does not start running a game although there 56 games and 209 cards remaining which could be farmed. Changing Farming behavior in the settings didn't do anything. Why does this happen?

![grafik](https://user-images.githubusercontent.com/65826571/151925834-c8321d88-1be0-4e75-b087-f0e7dcb75460.png)

P.S: ignore the language I can't change it for some reason xD

**Comment by DerrFloh** [comment]
Ok so I found out what the problem is:

If you run the Application and there's no steam_api.dll and steam-idle file it creates (or updates) it in the folder of the source. So if I have a link to the IdleMasterExtended.exe those files are created in the folder of the link:
![grafik](https://user-images.githubusercontent.com/65826571/152108693-24927c30-6d2d-4c07-bea8-8532ea47563d.png)
So if you make a Windows start menu link (and start it), it seems like the application does not know where to create those files so it doesn't and therefore can't work. 

So the start menu link which I had was the reason of it not working properly. It was also the reason of why I couldn't change the language

**Comment by JonasNilson** [comment]
Thanks for the detailed bug report.

I have not seen anything similar before so this will likely help in the future when someone else stumbles upon a similar issue.
