### ISSUE TITLE
unknown publisher

### ISSUE THREAD

**Issue by domashenterlik** [JonasNilson/idle_master_extended#299]
so i was downloading it. i ran the program and windows said :unknown publisher.
I am asking if its a virus or not.
Also I ran a scan with virus total and it said it was a virus

**Comment by XdekHckr** [comment]
> so i was downloading it. i ran the program and windows said :unknown publisher. I am asking if its a virus or not. Also I ran a scan with virus total and it said it was a virus

You can compile it by yourself if you don't trust it and view source code. User issue - thread closed.

**Comment by JonasNilson** [comment]
Unknown publisher is due to the application not being signed. I could sign it but so could anyone and it's not so easy to get a reputable certification for code signing: https://docs.microsoft.com/en-gb/archive/blogs/ieinternals/everything-you-need-to-know-about-authenticode-code-signing

The virus part is probably related to #295
