### ISSUE TITLE
[Whitelist] problem with the whitelist mode

### ISSUE THREAD

**Issue by thomasabd23** [JonasNilson/idle_master_extended#391]
Hello. There is a problem with the whitelist mode. It's idling the games that have 0 card drops remaining. I picked 29 games and all 29 games are idling now

**Comment by LucaMacTavish2502** [comment]
I also have a problem with Whitelist mode and the Idle Master itself. I have many games with achievable chromes, but it only picked Killing Floor 1 and Vector. And it didn't even unlocked them all. And on Whitelist mode, I place the app ID as requested, but it remains loading forever.

**Comment by thomasabd23** [comment]
I hope developer will respond :(

**Comment by jonas-med-ett-s** [comment]
> It's idling the games that have 0 card drops remaining. 

The whitelist mode will ignore the check for card drops and idle all the games you have added to the whitelist. [Read more in the Wiki on Whitelist mode](https://github.com/JonasNilson/idle_master_extended/wiki/Whitelist-mode).

> I have many games with achievable chromes... And on Whitelist mode, I place the app ID as requested, but it remains loading forever.

You have probably received all the card drops you are eligible for on those games. Check under your badge page ([read more in the FAQ](https://github.com/JonasNilson/idle_master_extended/wiki/FAQ#why-dont-i-get-all-the-cards-for-a-badge)): 
![image](https://user-images.githubusercontent.com/5990550/214111542-17c1492f-1e7b-4383-8ff6-a7e3a36cad33.png)

**Comment by LucaMacTavish2502** [comment]
So, in the end, it means that Whitelist mode is useless, right?

**Comment by LucaMacTavish2502** [comment]
The description says this: Add any game for idling on Steam. This will ignore if the game has card drops remaining or not.
But, in my case, IT DOESN'T IGNORE THE FACT THAT I DON'T HAVE CARD DROPS REMAINING. This will need fixing ASAP.

**Comment by jonas-med-ett-s** [comment]
> But, in my case, IT DOESN'T IGNORE THE FACT THAT I DON'T HAVE CARD DROPS REMAINING. This will need fixing ASAP.

Please elaborate. What games have you added to the whitelist, how does it behave and how do you expect it to behave?

What settings do you have enabled in your Idle Master Extended application?

**Comment by LucaMacTavish2502** [comment]
![Captura de pantalla 2023-01-25 170810](https://user-images.githubusercontent.com/123219461/214678768-fd59093a-d1c3-4f68-9bc9-f742684ee651.png)
My settings

![Captura de pantalla 2023-01-25 170856](https://user-images.githubusercontent.com/123219461/214678839-112aef1b-43b4-49db-868a-f5773feb7533.png)
My games: 
Apex legends
Counter strike global offensive
Counter strike nexon studio
Insurgency sandstorm
Killing floor
Killing floor 2
Need for speed heat
Resident evil 6
Vector
Warface
World of tanks

![Captura de pantalla 2023-01-25 171010](https://user-images.githubusercontent.com/123219461/214679488-f17f0b27-40e3-4a02-903c-beefe9ee78b1.png)
I expect it to farm, but it remains like this for hours and never farms.

**Comment by Cabola** [comment]
It does exactly what it's suppose to do, it idles the games. The whitelist only adds time to the games nothing else, or at least that's how it has always worked for me...

Sometime you need to add play time to a game, and this is where the whitelist comes in handy. Ex. if you wish to use points to buy something like chat emojis or what ever from the points shop. For some items it requires for you to have played the game for xx amount of time, before you're able to buy anything with your points related to that game.


Because of that I wish there were an option to idle all games to xx hours, instead of you having to manually add all game id's into the whitelist and then keep an eye on what each games time is at in the list to go into the whitelist and remove them manually along the idle process.

It would be much easier to make it just idle all games and then skip the games that are past xx play hours. Pretty much like it does with cards just with play time instead..

**Comment by LucaMacTavish2502** [comment]
I'm done with this. I give up.
