### ISSUE TITLE
[BUG] Games Not Working

### ISSUE THREAD

**Issue by Haxnstuff** [JonasNilson/idle_master_extended#406]
Only one of my games semi works, it pops up then repeatedly tries to get cards from it (it's gmod) but fails, I also have a ton of other games that have cards but they don't even pop up in the que.

**Comment by jonas-med-ett-s** [comment]
>  it pops up then repeatedly tries to get cards from it (it's gmod) but fails

This is likely due to not having reached the required hours in-game for the cards to drop. The repeated popups is likely due to the `Fast mode` (can be changed in the application settings, under `File > Settings > Idling mode`):
- https://github.com/JonasNilson/idle_master_extended/wiki/Fast-mode

> I also have a ton of other games that have cards but they don't even pop up in the que

My guess is that you don't have any card drops remaining for those games:
- https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by LeonardoDCunha** [comment]
yes, it happened to me too since the 26th
