### ISSUE TITLE
idlemaster is not giving any cards help me

### ISSUE THREAD

**Issue by Laustre** [JonasNilson/idle_master_extended#48]
its not giving any cards i have 3 card drops it didnt give any i tried 3 games yestreday with 9 card it didnt work either

**Comment by JonasNilson** [comment]
> its not giving any cards i have 3 card drops it didnt give any i tried 3 games yestreday with 9 card it didnt work either

What games do you have card drops available for?

Can you provide a screenshot showing the issue?

**Comment by Laustre** [comment]
I had 3 hentai games and zup x but i refunded them because they were not
giving any card they had 12 card drops or 13

**Comment by JonasNilson** [comment]
> I had 3 hentai games and zup x but i refunded them because they were not giving any card they had 12 card drops or 13

It could be related to this post by jshackles (creator of Idle Master): https://steamcommunity.com/groups/idlemastery/announcements/detail/203007488879621804

In short you might need to idle the game for two hours before getting a card drop. This is due to Valves policy to avoid having people buy a game, get the trading cards, and then refund the game.

> More then 2 hours to drop first card? If you refund on Steam before, you might got this punishment. 
Source: https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/
