### ISSUE TITLE
[BUG] Doesnt works with family-shared games

### ISSUE THREAD

**Issue by YiitWT** [JonasNilson/idle_master_extended#488]
## Describe the bug ##
IdleMaster wont recognize the family-shared games. I think it should be added.

## Expected behavior ##
Recognize the family-shared games
`)

**Comment by DanteZulli** [comment]
Family-shared games on Steam [are not eligible to receive card drops](https://steamcommunity.com/discussions/forum/1/558750985779273719/) because they do not belong directly to the user trying to farm them. Steam has this restriction to prevent abuse of the card drop system, as cards are only generated for the legitimate owner of the game.

This means that even though you can play a shared game, IdleMaster or similar tools won't recognize these titles as valid for farming cards. If you want to obtain cards from those games, you will need to purchase them directly on your account.

**Comment by YiitWT** [comment]
Tysm
