### ISSUE TITLE
support for linux and mac?

### ISSUE THREAD

**Issue by barfin** [JonasNilson/idle_master_extended#72]

**Comment by JonasNilson** [comment]
You can try: https://github.com/jshackles/idle_master_py

**Comment by lexfrei** [comment]
Is there any chance of reopening this ticket? :)

**Comment by marekkloc1** [comment]
That would be a good idea, because i am linux user and launching it through the python file is hard for me, because i really don't know about programing in python, so launching it would be better in execuable file like what i use is xTerm console. I also see that the problem isn't just with launching, but also with logging in with steam. I would also greatly appreciate if there was an option for idle hours only games, not steam cards.
