### ISSUE TITLE
Don't Work

### ISSUE THREAD

**Issue by Khafa56** [JonasNilson/idle_master_extended#97]
Hey So i've Been Waiting For Like 1 Hour And No Cards Appear In My Account

**Comment by Khafa56** [comment]
![Capture](https://user-images.githubusercontent.com/69250353/89419608-be203900-d75b-11ea-9926-d8fa8af156f2.PNG)

**Comment by Khafa56** [comment]
Thats What It Looks Like

**Comment by JonasNilson** [comment]
Is this still an issue? Some accounts will take over 2 hours for cards to drop due to certain criterias (for example if you have returned a game you've bought)

Some information can be found here:
* https://steamcommunity.com/groups/idlemastery/announcements/detail/203007488879621804
* https://steamcommunity.com/groups/tradingcards/discussions/1/1480982971163403431/

**Comment by Khafa56** [comment]
Yes This Is Still An Issue,Ill Try To Wait 2 Hour And See If Theres Any UpdatesThanks!

**Comment by Khafa56** [comment]
Btw,Just Want To As Is This Normal?

![Capture1](https://user-images.githubusercontent.com/69250353/89471781-36f9b200-d7a9-11ea-9953-c888e9ef4882.PNG)

**Comment by JonasNilson** [comment]
@Khafa56 Looks normal, but are if you want to use your whitelist you should activate it under File > Settings > whitelist mode
